baseURL      = "http://praveenmuthu.dev"
languageCode = "en-us"
title        = "Praveen Muthu"
theme        = "hugo-theme-console"

[params]
  titleCutting = true

  animateStyle = "animated zoomIn fast"

  [[params.navlinks]]
  name = "home"
  url  = "/"  

  [[params.navlinks]]
  name = "about/"
  url  = "about/"

  [[params.navlinks]]
  name = "resume/"
  url  = "resume/"

  [[params.navlinks]]
  name = "portfolio/"
  url  = "portfolio/"